// Red Colors
export const lightsalmon = '#ffa07a'
export const salmon = '#fa8072'
export const darksalmon = '#e9967a'
export const lightcoral = '#f08080'
export const indianred = '#cd5c5c'
export const crimson = '#dc143c'
export const firebrick = '#b22222'
export const red = '#ff0000'

//Orange Colors
export const coral = '#ff7f50'
export const tomato = '#ff6347'
export const orangered = '#ff4500'
export const gold = '#ffd700'
export const orange = '#ffa500'
export const darkorange = '#ff8c00'

//Yellow Colors
export const lightyellow = '#ffffe0'
export const lemonchiffon = '#fffacd'
export const lightgoldenrodyellow = '#fafad2'
export const papayawhip = '#ffefd5'
export const moccasin = '#ffe4b5'
export const peachpuff = '#ffdab9'
export const palegoldenrod = '#eee8aa'
export const khaki = '#f0e68c'
export const darkkhaki = '#bdb76b'
export const yellow = '#ffff00'

//Green Colors
export const lawngreen = '#7cfc00'
export const chartreuse = '#7fff00'
export const limegreen = '#32cd32'
export const lime = '#00ff00'
export const forestgreen = '#228b22'
export const green = '#008000'
export const darkgreen = '#006400'
export const greenyellow = '#adff2f'
export const yellowgreen = '#9acd32'
export const springgreen = '#00ff7f'
export const mediumspringgreen = '#00fa9a'
export const lightgreen = '#90ee90'
export const palegreen = '#98fb98'
export const darkseagreen = '#8fbc8f'
export const mediumseagreen = '#3cb371'
export const seagreen = '#2e8b57'
export const olive = '#808000'
export const darkolivegreen = '#556b2f'
export const olivedrab = '#6b8e23'

//Cyan Colors
export const lightcyan = '#e0ffff'
export const cyan = '#00ffff'
export const aqua = '#00ffff'
export const aquamarine = '#7fffd4'
export const mediumaquamarine = '#66cdaa'
export const paleturquoise = '#afeeee'
export const turquoise = '#40e0d0'
export const mediumturquoise = '#48d1cc'
export const darkturquoise = '#00ced1'
export const lightseagreen = '#20b2aa'
export const cadetblue = '#5f9ea0'
export const darkcyan = '#008b8b'
export const teal = '#008080'

//Blue Colors
export const powderblue = '#b0e0e6'
export const lightblue = '#add8e6'
export const lightskyblue = '#87cefa'
export const skyblue = '#87ceeb'
export const deepskyblue = '#00bfff'
export const lightsteelblue = '#b0c4de'
export const dodgerblue = '#1e90ff'
export const cornflowerblue = '#6495ed'
export const steelblue = '#4682b4'
export const royalblue = '#4169e1'
export const blue = '#0000ff'
export const mediumblue = '#0000cd'
export const darkblue = '#00008b'
export const navy = '#000080'
export const midnightblue = '#191970'
export const mediumslateblue = '#7b68ee'
export const slateblue = '#6a5acd'
export const darkslateblue = '#483d8b'

//Purple Colors
export const lavender = '#e6e6fa'
export const thistle = '#d8bfd8'
export const plum = '#dda0dd'
export const violet = '#ee82ee'
export const orchid = '#da70d6'
export const fuchsia = '#ff00ff'
export const magenta = '#ff00ff'
export const mediumorchid = '#ba55d3'
export const mediumpurple = '#9370db'
export const blueviolet = '#8a2be2'
export const darkviolet = '#9400d3'
export const darkorchid = '#9932cc'
export const darkmagenta = '#8b008b'
export const purple = '#800080'
export const indigo = '#4b0082'

//Pink Colors
export const pink = '#ffc0cb'
export const lightpink = '#ffb6c1'
export const hotpink = '#ff69b4'
export const deeppink = '#ff1493'
export const palevioletred = '#db7093'
export const mediumvioletred = '#c71585'

//White Colors
export const white = '#ffffff'
export const snow = '#fffafa'
export const honeydew = '#f0fff0'
export const mintcream = '#f5fffa'
export const azure = '#f0ffff'
export const aliceblue = '#f0f8ff'
export const ghostwhite = '#f8f8ff'
export const whitesmoke = '#f5f5f5'
export const seashell = '#fff5ee'
export const beige = '#f5f5dc'
export const oldlace = '#fdf5e6'
export const floralwhite = '#fffaf0'
export const ivory = '#fffff0'
export const antiquewhite = '#faebd7'
export const linen = '#faf0e6'
export const lavenderblush = '#fff0f5'
export const mistyrose = '#ffe4e1'

//Gray Colors
export const gainsboro = '#dcdcdc'
export const lightgray = '#d3d3d3'
export const silver = '#c0c0c0'
export const darkgray = '#a9a9a9'
export const gray = '#808080'
export const dimgray = '#696969'
export const lightslategray = '#778899'
export const slategray = '#708090'
export const darkslategray = '#2f4f4f'
export const black = '#000000'

//Brown Colors
export const cornsilk = '#fff8dc'
export const blanchedalmond = '#ffebcd'
export const bisque = '#ffe4c4'
export const navajowhite = '#ffdead'
export const wheat = '#f5deb3'
export const burlywood = '#deb887'
export const tan = '#d2b48c'
export const rosybrown = '#bc8f8f'
export const sandybrown = '#f4a460'
export const goldenrod = '#daa520'
export const peru = '#cd853f'
export const chocolate = '#d2691e'
export const saddlebrown = '#8b4513'
export const sienna = '#a0522d'
export const brown = '#a52a2a'
export const marron = '#800000'